services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          memory: 128m  # AWS t2.large -> 256m
          cpus: "0.2"

  api1:
    build:
      context: ./api_server
    environment:
      - APP_PORT=8888
    ports:
      - "8888:8888"
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          memory: 512m  # AWS t2.large -> 768m
          cpus: "0.5"

  api2:
    build:
      context: ./api_server
    environment:
      - APP_PORT=8889
    ports:
      - "8889:8889"
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          memory: 512m  # AWS t2.large -> 768m
          cpus: "0.5"

  #stt:
  #  build:
  #    context: ./stt_server
  #  command: uvicorn stt_server:app --host 0.0.0.0 --port 8001
  #  ports:
  #    - "8001:8001"
  #  depends_on:
  #    - kafka
  #  deploy:
  #    resources:
  #      limits:
  #        memory: 512m  # AWS t2.large -> 768m
  #        cpus: "0.5"

  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_KRAFT_MODE=false
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://34.47.117.122:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_USER=myuser
      - KAFKA_ZOOKEEPER_PASSWORD=mypassword
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          memory: 1g    # AWS t2.large -> 1.5g
          cpus: "0.3"

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=myuser
      - ZOO_SERVER_PASSWORDS=mypassword
    deploy:
      resources:
        limits:
          memory: 256m  # AWS t2.large -> 512m
          cpus: "0.2"
